NAME	=	polymorphism

SRCS	=	main.cpp		\
			Animal.cpp		\
			Cat.cpp			\
			Dog.cpp			\
			WrongAnimal.cpp	\
			WrongCat.cpp

INCS	=	Animal.hpp		\
			Cat.hpp			\
			Dog.hpp			\
			WrongAnimal.hpp

include ../template.mk
